spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:

taco:
  orders:
    page-size: 10

logging:
  level:
    tacos: DEBUG

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://localhost:3306/tacocloud
    username: tacouser
    password: tacopassword

logging:
  level:
    tacos: WARN

